#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH --mem 20000 # 2GB solicitados.
#SBATCH -p mhigh,mlow # or mlow Partition to submit to
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o test_vr/prova/%x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e test_vr/prova/%x_%u_%j.err # File to which STDERR will be written
python rmain.py --silent --exp_name prova2 --exp_folder test_vr --config_file config/SemSeg_sample_fcn8_Camvid_vr.yml
