#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH --mem 20000 # 2GB solicitados.
#SBATCH -p mhigh,mlow # or mlow Partition to submit to
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o logs/%x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e logs/%x_%u_%j.err # File to which STDERR will be written
python main.py --silent --exp_name testunet02 --exp_folder test04 --config_file config/SemSeg_sample_Camvid_ResNetUnet.yml
