#!/bin/bash
#SBATCH --array=1-8
#SBATCH -n 4 # Number of cores
#SBATCH --mem 34000 # 2GB solicitados.
#SBATCH -p mhigh,mlow # or mlow Partition to submit to
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o logs/unet/%x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e logs/unet/%x_%u_%j.err # File to which STDERR will be written

python main.py --silent --exp_name prova_${SLURM_ARRAY_TASK_ID} --exp_folder test_unet --config_file config/config_2/SemSeg_sample_Camvid_unet_${SLURM_ARRAY_TASK_ID}.yml

