#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH --mem 16000 # 2GB solicitados.
#SBATCH -p mhigh,mlow # or mlow Partition to submit to
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o logs/%x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e logs/%x_%u_%j.err # File to which STDERR will be written
python2 main.py --exp_name test2 --exp_folder test_experiment --config_file config/classification_sample_vgg16_tt100k_pre.yml

